package employees

var employeesList = Employees{
	{"Alice Johnson", "Software Engineer", "Passionate about backend development.", []string{"Go", "Microservices"}},
	{"Bob Smith", "Frontend Developer", "Loves creating beautiful UI.", []string{"React", "CSS"}},
	{"Charlie Brown", "DevOps Engineer", "Ensures smooth CI/CD pipelines.", []string{"Docker", "Kubernetes"}},
	{"David Wilson", "Product Manager", "Drives product vision and strategy.", []string{"Agile", "User Research"}},
	{"Eve Adams", "Data Scientist", "Expert in AI and ML.", []string{"Python", "TensorFlow"}},
	{"Frank White", "Security Engineer", "Focuses on cybersecurity best practices.", []string{"Testing", "Cryptography"}},
	{"Grace Hall", "UX Designer", "Creates intuitive and accessible designs.", []string{"Figma", "UX"}},
	{"Henry King", "System Administrator", "Manages IT infrastructure.", []string{"Linux", "Networking"}},
	{"Isabel Scott", "Software Architect", "Designs scalable software solutions.", []string{"Go", "Architecture"}},
	{"Jack Lee", "QA Engineer", "Ensures software quality through testing.", []string{"Selenium", "CI/CD"}},

	{"Laura Miller", "Mobile Developer", "Builds mobile applications.", []string{"Swift", "iOS"}},
	{"Nathan Green", "Backend Engineer", "Optimizes APIs and services.", []string{"Node.js", "Databases"}},
	{"Olivia Brown", "AI Engineer", "Creates AI-driven solutions.", []string{"Python", "Machine Learning"}},
	{"Peter Wilson", "Cloud Engineer", "Works with cloud infrastructure.", []string{"AWS", "Terraform"}},
	{"Quinn Adams", "Blockchain Developer", "Develops blockchain applications.", []string{"Solidity", "Ethereum"}},
	{"Rachel White", "Game Developer", "Creates immersive gaming experiences.", []string{"Unity", "C#"}},
	{"Samuel Harris", "Embedded Engineer", "Develops firmware for devices.", []string{"C", "Microcontrollers"}},
	{"Tina Robinson", "Tech Support", "Helps users solve tech issues.", []string{"Troubleshooting", "Helpdesk"}},
	{"Umar Davis", "IT Consultant", "Provides tech solutions.", []string{"Cloud", "Security"}},
	{"Victor Evans", "Database Administrator", "Manages databases.", []string{"PostgreSQL", "Optimization"}},

	{"Wendy Collins", "Software Engineer", "Writes efficient and scalable code.", []string{"Java", "Spring"}},
	{"Xavier Martin", "Data Engineer", "Processes large datasets.", []string{"Hadoop", "ETL"}},
	{"Yasmine Carter", "Network Engineer", "Manages network security.", []string{"Cisco", "Firewalls"}},
	{"Zack Nelson", "Hardware Engineer", "Designs and tests hardware.", []string{"PCB", "Microcontrollers"}},
	{"Abby Cooper", "Full Stack Developer", "Builds end-to-end solutions.", []string{"React", "Node.js"}},
	{"Ben Parker", "Security Analyst", "Analyzes security threats.", []string{"Pentesting", "Compliance"}},
	{"Catherine James", "DevOps Engineer", "Improves deployment pipelines.", []string{"CI/CD", "Kubernetes"}},
	{"Daniel Harris", "Software Engineer", "Focuses on high-performance code.", []string{"C++", "Algorithms"}},
	{"Elena Ford", "Product Designer", "Designs product experiences.", []string{"Figma", "UI/UX"}},
	{"Felix Ramirez", "Backend Developer", "Optimizes APIs for scale.", []string{"Django", "PostgreSQL"}},

	{"George Clarke", "AI Researcher", "Explores AI advancements.", []string{"Deep Learning", "NLP"}},
	{"Hannah Adams", "Frontend Developer", "Builds modern web interfaces.", []string{"Vue.js", "Tailwind"}},
	{"Ian Peterson", "Cybersecurity Expert", "Enhances security protocols.", []string{"Encryption", "Ethical Hacking"}},
	{"Jane Lopez", "Game Designer", "Crafts engaging game mechanics.", []string{"Game Theory", "C#"}},
	{"Kevin Hughes", "Cloud Security Engineer", "Secures cloud environments.", []string{"AWS", "IAM"}},
	{"Lily Bennett", "Scrum Master", "Facilitates agile teams.", []string{"Scrum", "Kanban"}},
	{"Matthew Diaz", "Software Developer", "Writes clean and maintainable code.", []string{"Rust", "Concurrency"}},
	{"Nina Torres", "Data Analyst", "Derives insights from data.", []string{"SQL", "Power BI"}},
	{"Oscar Knight", "Full Stack Developer", "Works on front and backend.", []string{"Next.js", "MongoDB"}},
	{"Paula Simmons", "Robotics Engineer", "Builds intelligent robots.", []string{"ROS", "Python"}},

	{"Quincy Ross", "System Engineer", "Optimizes IT systems.", []string{"Windows", "VMWare"}},
	{"Rebecca Adams", "AI Product Manager", "Manages AI-driven products.", []string{"AI", "Product Strategy"}},
	{"Steve Duncan", "Game Developer", "Creates 3D games.", []string{"Unity", "C#"}},
	{"Tommy Fox", "Embedded Systems Engineer", "Works on low-level systems.", []string{"C", "RTOS"}},
	{"Ursula Novak", "Tech Writer", "Writes technical documentation.", []string{"Markdown", "API Docs"}},
	{"Victor Stone", "DevSecOps Engineer", "Ensures secure CI/CD.", []string{"DevOps", "Security"}},
	{"Wendy Foster", "IT Support Engineer", "Solves technical problems.", []string{"Helpdesk", "Networking"}},
	{"Xander Lee", "SRE", "Maintains service reliability.", []string{"Kubernetes", "Observability"}},
	{"Yara Clarke", "SEO Specialist", "Optimizes websites for search engines.", []string{"SEO", "Analytics"}},
	{"Zane Williams", "Growth Engineer", "Drives growth through tech.", []string{"A/B Testing", "Data"}},

	{"Aaron Miles", "ML Engineer", "Builds AI models.", []string{"TensorFlow", "Deep Learning"}},
	{"Becky Olsen", "Hardware Tester", "Tests hardware products.", []string{"Quality Control", "Circuits"}},
	{"Carlos Gomez", "Smart Contract Developer", "Works on blockchain projects.", []string{"Solidity", "Web3"}},
	{"Diana Roberts", "E-commerce Developer", "Builds online store platforms.", []string{"Shopify", "WooCommerce"}},
	{"Elliot Brooks", "DevOps Specialist", "Automates infrastructure.", []string{"Terraform", "CI/CD"}},
	{"Fiona Woods", "Mobile App Designer", "Designs mobile UI.", []string{"Figma", "UX"}},
	{"Graham Norton", "Performance Engineer", "Optimizes app performance.", []string{"Profiling", "Caching"}},
	{"Holly Patterson", "3D Artist", "Creates digital 3D assets.", []string{"Blender", "Maya"}},
	{"Isaac Martinez", "Data Visualization Expert", "Creates insightful dashboards.", []string{"D3.js", "Tableau"}},
	{"Julia Fernandez", "Tech Recruiter", "Finds top tech talent.", []string{"Hiring", "Interviewing"}},
}
